### ISSUE TITLE
Player Location POI broken

### ISSUE THREAD

**Issue by Fiuse** [overviewer/Minecraft-Overviewer#1778]
def playerIcons(poi):
        if poi['id']=='Player':
                poi['icon']="http://overviewer.org/avatar/%s" % poi['EntityId']
                return "Last known location for %s" % poi['EntityId']

no longer shows the players location in the most recent snapshot due to a change in the dimension keyword in the player.dat being changed from an int to a string. (Ex: what was once Dimesnion: 0 is now Dimesnion: minecraft:overworld).

**Comment by jobe1986** [comment]
I can confirm that players connecting to 1.16 and later do not get passed to the players filter function.

**Comment by CounterPillow** [comment]
Fixed, haven't tested with the nether yet but it should work in theory. Let me know if it's totally broken or something.

**Comment by jobe1986** [comment]
Well, I haven't been able to test for minecraft:the_nether yet, as none of my players were there for the test, however it definitely works for minecraft:the_end and minecraft:overworld.

Though there is one minor issue, Players that haven't connected since 1.16 still have the old integer dimension values and as a result are no longer shown.

I don't personally see that as a bug but it would be nice if they'd still be shown too.

**Comment by CounterPillow** [comment]
>Though there is one minor issue, Players that haven't connected since 1.16 still have the old integer dimension values and as a result are no longer shown.

This is weird because this case should be handled, actually. I'll look into it.

**Comment by CounterPillow** [comment]
Okay, now it's fixed.

**Comment by jobe1986** [comment]
That appears to have fixed it thanks.
